# Generated by Django 3.0.8 on 2020-07-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_university', models.CharField(max_length=40)),
                ('city_of_university', models.CharField(max_length=40)),
                ('country_of_university', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_degree', models.CharField(max_length=50)),
                ('type_of_degree', models.CharField(choices=[('Masters', 'Masters'), ('Bachelor', 'Bachelor'), ('PhD', 'PhD')], max_length=10)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5)),
                ('university', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cv.University')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True)),
                ('first_degree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_degree', to='cv.Degree')),
                ('second_degree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_degree', to='cv.Degree')),
                ('third_degree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_degree', to='cv.Degree')),
            ],
        ),
    ]
